version: '3'

services:
    testing-suite:
        build:
          context: ./Docker
       # command: "./bin/run -e ${TEST_ENV} -b ${TEST_BROWSER} -k ${TEST_QKSKEY} -g ${TEST_GROUP} -t ${TEST_RUNTYPE}"
       
       # working_dir: /testing-suite
       
        command: "./bin/run beta chrome checkAllLinks ONG2XB update"
        volumes:
            #- "${HOST_PATH_SRC_TEST_SUITE}:/testing-suite"
            - .:/project
        depends_on:
            - selenium-chrome
   

    selenium-chrome:
        image: selenium/standalone-chrome:3.5.3
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
