version: 2
jobs:
    build:
        docker:
            - {image: 'circleci/php:7.1.16'}

          
        steps:
            - checkout
            - {run: 'echo "A first hello"'}
            - {run: 'pwd'}
            - {run: 'ls'}
            - {run: 'php -v'}
            - {run: 'php --ini'}

           
            - {run: 'php --ini'}
           
workflows:
    version: 2
    Regression-tests:
        jobs:
            - build:
                filters:
                   branches:
                      only: master
