version: 2
jobs:
    build:
        docker:
            - {image: 'circleci/php:7.1.16'}
        steps:
            - checkout
            - {run: 'echo $key'}

workflows:
    version: 2
    Regression-tests:
        jobs:
            - build
