version: 2
jobs:
    build:
        docker:
            - {image: 'circleci/php:7.1.16'}
        steps:
            - checkout
            - {run: 'echo "run build"'}

    Run-unit-tests:
        machine:
            enabled: true
        steps:
            - {run: 'echo "Run-unit-tests"'}         
            
    Run-Integration-tests:
        machine:
            enabled: true
        steps:
            - {run: 'echo "Run-Integration-tests"'} 

    Run-Regression-tests:
        machine:
            enabled: true
        steps:
            - {run: 'echo "Run-Regression-tests"'} 
    deploy:
        machine:
            enabled: true
        steps:
            - {run: 'echo "Run-deployemnt"'}             

workflows:
    version: 2
    Regression-tests:
        jobs:
            - build
            - Run-unit-tests:
                requires:
                    - build
            - Run-Integration-tests:
                requires:
                    - build        
            - Run-Regression-tests:
                requires:
                    - build
            - hold:
                type: approval
            -deploy:
                requires:
                    - hold       
