version: 2
jobs:
    build:
        docker:
            - {image: 'circleci/php:7.1.16'}
            #- {image: 'halplatform/hal-build-environments:php7.1-centos7'}
          
        steps:
            - checkout
            - {run: 'echo "A first hello"'}
            - {run: 'pwd'}
            - {run: 'ls'}
            - {run: 'php -v'}
            - {run: 'php --ini'}
            - {run: 'sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev'}
            - {run: 'sudo docker-php-ext-install zip'}
            - {run: 'sudo apt-get install -y libpng-dev'}
            - {run: 'sudo docker-php-ext-install gd'}
            - {run:  'composer install -n --prefer-dist'}
           
            - {run: 'php --ini'}
           
workflows:
    version: 2
    Regression-tests:
        jobs:
            - build
