version: 2
jobs:
    Run-Regression-tests:
        docker:
            - {image: 'circleci/php:7.1.16'}
        steps:
            - checkout
            - {run: 'echo "A first hello"'}
            - {run: 'docker --version'}
            - {run: 'echo "A second hello"'}
            - {run: 'echo "A third hello"'}
            - {run: 'echo "A fourth hello"'}
            - {run: 'echo "A fifth hello"'}
    Run-Integration-tests:
        docker:
            - {image: 'circleci/php:7.1.16'}
        steps:
            - {run: 'echo "Run-Integration-tests"'}        
workflows:
    version: 2
    Regression-tests:
        jobs:
            - Run-Regression-tests
            - Run-Integration-tests:
                requires:
                    - Run-Regression-tests
