version: 2
jobs:
    Run-Regression-tests:
        docker:
            - {image: 'circleci/php:7.1.16'}
        steps:
            - checkout
            - {run: 'echo "A first hello"'}
workflows:
    version: 2
    Regression-tests:
        jobs:
            - Run-Regression-tests
