version: 2
jobs:
    build:
        docker:
            - {image: 'circleci/php:7.1.16'}
        steps:
            - checkout
            - {run: 'echo "run build"'}

    Run-Regression-tests:
        machine:
            enabled: true
        steps:
            - {run: 'echo "Run-Regression-tests"'} 


    deploy:
            
        machine:
            enabled: true
        steps:
            - {run: 'echo "Run-Deployment"'}             
            

workflows:
    version: 2
    Regression-tests:
        jobs:
            - build      
            - Run-Regression-tests:
                requires:
                    - build
            -hold:
                type: approval
                requires: 
                    - Run-Regression-tests
            -deploy:
                requires:
                    - hold  
